name:         "Matt Wondra&rsquo;s Blog"
url:          "http://mattwondra.com"
description:  "Thoughts on web development, design process, and remote work by Matt Wondra."
author:       "Matt Wondra"

defaultFlavorText: forgot to add flavor text to this page.

permalink: /:year/:title/



highlighter: pygments
markdown: redcarpet
sass:
  sass_dir: assets/_sass

# Options for jekyll-rss plugin
# rss_path:       "/"
# rss_name:       "rss.xml"
# rss_post_limit: 10